# Generated by Django 4.0.4 on 2026-01-22 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardOpenTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('D', 'Draft'), ('A', 'Active'), ('P', 'Purge')], db_index=True, default='A', max_length=1)),
                ('is_default', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarifs.cardopentarif')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardTopUpTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('D', 'Draft'), ('A', 'Active'), ('P', 'Purge')], db_index=True, default='A', max_length=1)),
                ('is_default', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarifs.cardtopuptarif')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepositTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('D', 'Draft'), ('A', 'Active'), ('P', 'Purge')], db_index=True, default='A', max_length=1)),
                ('is_default', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarifs.deposittarif')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('D', 'Draft'), ('A', 'Active'), ('P', 'Purge')], db_index=True, default='A', max_length=1)),
                ('is_default', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarifs.exchangetarif')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawTarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('D', 'Draft'), ('A', 'Active'), ('P', 'Purge')], db_index=True, default='A', max_length=1)),
                ('is_default', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarifs.withdrawtarif')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawTarifLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('fee_percent', models.DecimalField(decimal_places=3, default=1.0, max_digits=6, verbose_name='Fee, %')),
                ('fee_fixed', models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Fee, fixed')),
                ('fee_minimal', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Fee, minimal')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Min amount')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Max amount')),
                ('method', models.CharField(blank=True, choices=[('CPT', 'Crypto'), ('MNL', 'Manual'), ('EXC', 'Exchange'), ('VC', 'VirtualCard')], db_index=True, default='', max_length=3)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tarifs.withdrawtarif')),
            ],
            options={
                'ordering': ('pk',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeTarifLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('fee_percent', models.DecimalField(decimal_places=3, default=1.0, max_digits=6, verbose_name='Fee, %')),
                ('fee_fixed', models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Fee, fixed')),
                ('fee_minimal', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Fee, minimal')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Min amount')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Max amount')),
                ('additional_rate_percent', models.DecimalField(decimal_places=3, default=1.0, max_digits=6, verbose_name='Additional rate, %')),
                ('additional_human_rate_percent', models.DecimalField(decimal_places=3, default=1.0, max_digits=6, verbose_name='Additional human rate, %')),
                ('currency_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarifs_from', to='currencies.currency')),
                ('currency_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarifs_to', to='currencies.currency')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tarifs.exchangetarif')),
            ],
            options={
                'ordering': ('pk',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepositTarifLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('fee_percent', models.DecimalField(decimal_places=3, default=1.0, max_digits=6, verbose_name='Fee, %')),
                ('fee_fixed', models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Fee, fixed')),
                ('fee_minimal', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Fee, minimal')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Min amount')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Max amount')),
                ('method', models.CharField(blank=True, choices=[('CPT', 'Crypto'), ('MNL', 'Manual'), ('EXC', 'Exchange'), ('VC', 'VirtualCard')], db_index=True, default='', max_length=3)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tarifs.deposittarif')),
            ],
            options={
                'ordering': ('pk',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardTopUpTarifLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('fee_percent', models.DecimalField(decimal_places=3, default=1.0, max_digits=6, verbose_name='Fee, %')),
                ('fee_fixed', models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Fee, fixed')),
                ('fee_minimal', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Fee, minimal')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Min amount')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Max amount')),
                ('method', models.CharField(blank=True, choices=[('CPT', 'Crypto'), ('MNL', 'Manual'), ('EXC', 'Exchange'), ('VC', 'VirtualCard')], db_index=True, default='', max_length=3)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tarifs.cardtopuptarif')),
            ],
            options={
                'ordering': ('pk',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardOpenTarifLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('fee_percent', models.DecimalField(decimal_places=3, default=1.0, max_digits=6, verbose_name='Fee, %')),
                ('fee_fixed', models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Fee, fixed')),
                ('fee_minimal', models.DecimalField(decimal_places=3, default=0.0, max_digits=6, verbose_name='Fee, minimal')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Min amount')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Max amount')),
                ('method', models.CharField(blank=True, choices=[('CPT', 'Crypto'), ('MNL', 'Manual'), ('EXC', 'Exchange'), ('VC', 'VirtualCard')], db_index=True, default='', max_length=3)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tarifs.cardopentarif')),
            ],
            options={
                'ordering': ('pk',),
                'abstract': False,
            },
        ),
    ]
