# Generated by Django 4.0.4 on 2026-01-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('S', 'System'), ('A', 'Active'), ('P', 'Purged')], db_index=True, default='D', max_length=1),
        ),
    ]
