# Generated by Django 4.0.6 on 2026-03-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_create_company_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password_salt',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='webauthn_credential_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='webauthn_public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
