# Generated by Django 4.0.4 on 2026-01-22 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import json.encoder
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('note', models.TextField(blank=True, default='', help_text='Вы можете добавить заметку, она не будет видна клиентам')),
                ('kind', models.CharField(choices=[('CO', 'CARD OPEN'), ('CU', 'CARD UPDATE'), ('CT', 'CARD TOPUP'), ('CB', 'CARD BLOCK'), ('CR', 'CARD RESTORE'), ('CC', 'CARD CLOSE'), ('CD', 'CARD BANNED'), ('DE', 'DEPOSIT'), ('WI', 'WITHDRAW'), ('SE', 'SERVICE'), ('SY', 'SYSTEM'), ('AJ', 'ADJUSTMENT')], db_index=True, max_length=2)),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('O', 'OPERATING'), ('C', 'COMPLETE'), ('F', 'FAILED'), ('U', 'UNKNOWN')], db_index=True, default='P', max_length=1)),
                ('is_final', models.BooleanField(blank=True, default=False)),
                ('method', models.CharField(choices=[('CPT', 'Crypto'), ('MNL', 'Manual'), ('EXC', 'Exchange'), ('VC', 'VirtualCard')], db_index=True, default='', max_length=3)),
                ('pending_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('operating_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('account_data', models.CharField(blank=True, db_index=True, help_text='PAN, Phone, SWIFT, etc.', max_length=64, null=True)),
                ('amount_db', models.BigIntegerField(blank=True, null=True)),
                ('fee_db', models.BigIntegerField(blank=True, null=True)),
                ('amount_done_db', models.BigIntegerField(blank=True, null=True)),
                ('amount_rest_db', models.BigIntegerField(blank=True, null=True)),
                ('data', models.JSONField(encoder=json.encoder.JSONEncoder)),
                ('tarif_id', models.PositiveIntegerField(null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='clients.account')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='clients.client')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.currency')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suboperations', to='operations.operation')),
            ],
        ),
    ]
