# Generated by Django 4.0.4 on 2026-02-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_gate_operation_gate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
