# Generated by Django 4.0.4 on 2026-02-20 11:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_gate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('tag', models.CharField(choices=[('CREATE', 'Create'), ('HOLD_AMOUNT', 'Hold amount'), ('UNHOLD_AMOUNT', 'UnHold amount'), ('TO_GATE', 'To Gate'), ('FROM_GATE', 'From Gate'), ('TO_FISCAL', 'To Fiscal'), ('FETCH_STATUS', 'Fetch status'), ('DONE', 'Done'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown'), ('ADDRESS_CHANGED', 'Address changed'), ('PROMOTED', 'Promoted')], max_length=24)),
                ('message', models.CharField(blank=True, max_length=256, null=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='operations.operation')),
            ],
            options={
                'db_table': 'operations_operationlog',
                'ordering': ['-created_at'],
            },
        ),
    ]
