# Generated by Django 4.0.4 on 2026-01-30 16:03

import common.serializers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMove',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_db', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('A', 'Approved')], db_index=True, default='D', max_length=1)),
                ('direction', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'finance_accountmove',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('A', 'Approved'), ('R', 'Rejected')], db_index=True, default='D', max_length=1)),
                ('kind', models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdraw'), ('M', 'Move'), ('F', 'Fee'), ('A', 'Adjustment'), ('T', 'Tax'), ('O', 'OverdraftFee')], db_index=True, max_length=1)),
                ('amount_db', models.BigIntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict, encoder=common.serializers.JSONEncoder)),
            ],
            options={
                'db_table': 'finance_transaction',
                'managed': False,
            },
        ),
    ]
