# Generated by Django 4.0.4 on 2026-01-22 13:05

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('F', 'Fiat'), ('C', 'Crypto')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('base', models.CharField(db_index=True, max_length=6)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('suffix', models.CharField(blank=True, default='', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('denominator', models.IntegerField(default=2)),
                ('human_denominator', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=18)),
                ('human_rate', models.DecimalField(decimal_places=10, default=Decimal('0.0'), max_digits=18)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_from', to='currencies.currency')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_to', to='currencies.currency')),
            ],
            options={
                'unique_together': {('currency_from', 'currency_to')},
            },
        ),
    ]
