import { createContext, useContext, useState, ReactNode } from 'react';

export type Lang = 'ru' | 'en';

const T = {
  ru: {
    // Statuses
    status_P: 'Ожидание',
    status_O: 'Обработка',
    status_C: 'Выполнено',
    status_F: 'Ошибка',
    status_U: 'Неизвестно',
    // Operation kinds
    kind_DE: 'Пополнение',
    kind_WI: 'Вывод',
    kind_CO: 'Выпуск карты',
    kind_CT: 'Пополнение карты',
    kind_CB: 'Заморозка карты',
    kind_CR: 'Разморозка карты',
    kind_CC: 'Закрытие карты',
    // History page
    filter_type: 'Тип операции',
    filter_status: 'Статус',
    no_ops: 'Операций пока нет',
    total: 'всего',
    prev: 'Назад',
    next: 'Далее',
    history_title: 'История',
    // Dashboard
    available: 'Доступно',
    total_balance: 'Общий баланс',
    greeting: 'Привет',
    recent_ops: 'Последние операции',
    all: 'Все',
    active_cards: 'Ваши карты',
    all_cards: 'Все карты',
    action_deposit: 'Пополнить',
    action_withdraw: 'Вывести',
    action_new_card: 'Новая карта',
    action_my_cards: 'Мои карты',
    action_history: 'История',
    // BottomNav
    nav_home: 'Главная',
    nav_cards: 'Карты',
    nav_history: 'История',
    nav_services: 'Сервисы',
    nav_profile: 'Профиль',
    // Route titles (Layout)
    title_cards: 'Мои карты',
    title_issue: 'Новая карта',
    title_deposit: 'Пополнение',
    title_withdraw: 'Вывод',
    title_profile: 'Профиль',
    title_referral: 'Реферальная программа',
    title_security: 'Безопасность',
    title_notifications: 'Уведомления',
    title_support: 'Поддержка',
    title_exchange: 'Обмен валют',
    title_tariffs: 'Тарифы и лимиты',
    title_services: 'Сервисы',
    title_faq: 'FAQ',
    title_card_topup: 'Пополнить карту',
    title_card_detail: 'Детали карты',
    // VirtualCard statuses
    card_status_active: 'Карта активна',
    card_status_frozen: 'Карта заморожена',
    card_status_closed: 'Карта закрыта',
    card_hide: 'Скрыть',
    // CardsPage
    filter_active: 'Активные',
    filter_frozen: 'Замороженные',
    filter_closed: 'Закрытые',
    filter_closing: 'Закрываются',
    no_cards: 'Карт пока нет',
    no_cards_desc: 'Выпустите виртуальную карту для онлайн-платежей',
    issue_first_card: 'Выпустить первую карту',
    issue_new_card: 'Выпустить новую карту',
    no_cards_status: 'Нет карт с таким статусом',
    // DepositPage
    deposit_network: 'Сеть',
    deposit_scan: 'Отсканируйте QR или скопируйте адрес',
    copy_address: 'Скопировать адрес',
    copied: 'Скопировано!',
    wallet_creating: 'Кошелёк создаётся. Пожалуйста, попробуйте позже.',
    deposit_warning: 'Отправляйте только USDT (TRC-20) на этот адрес. Отправка других токенов приведёт к безвозвратной потере средств.',
    // WithdrawPage
    withdraw_available: 'Доступно для вывода',
    main_account: 'Основной счёт',
    withdraw_amount_label: 'Сумма вывода',
    recipient_address: 'Адрес получателя',
    address_placeholder: 'USDT TRC-20 адрес (T...)',
    address_err_empty: 'Введите USDT TRC-20 адрес',
    address_err_invalid: 'Неверный формат TRC-20 адреса',
    fee_calc_title: 'Расчёт комиссии',
    tarif_label: 'Тариф',
    fee_label: 'Комиссия',
    total_debit: 'Итого к списанию',
    withdraw_network_warning: 'Выводите только через сеть TRON (TRC-20). Другие сети не поддерживаются.',
    calc_fee: 'Рассчитать комиссию',
    calculating: 'Расчёт...',
    do_withdraw: 'Вывести средства',
    confirm_withdraw_title: 'Подтверждение вывода',
    confirm_withdraw_btn: 'Вывести',
    amount_label: 'Сумма',
    total_label: 'Итого',
    withdraw_success_title: 'Заявка отправлена!',
    withdraw_success_desc: 'Запрос обрабатывается. Вы получите уведомление после завершения.',
    to_history: 'История операций',
    to_home: 'На главную',
    free: 'Бесплатно',
    fixed_fee: 'фикс.',
    min_fee: 'мин.',
    // CardDetailPage
    card_credentials: 'Реквизиты карты',
    btn_show: 'Показать',
    btn_hide: 'Скрыть',
    card_number_label: 'Номер карты',
    expiry_label: 'Срок действия',
    topup_card: 'Пополнить карту',
    block_card: 'Заблокировать карту',
    unblock_card: 'Разблокировать карту',
    close_card: 'Закрыть карту',
    return_to_card: 'Вернуться к карте',
    card_blocking: 'Блокировка карты...',
    card_blocked_done: 'Карта заблокирована',
    card_restoring: 'Восстановление карты...',
    card_restored_done: 'Карта восстановлена',
    card_closing_op: 'Закрытие карты...',
    card_closed_done: 'Карта закрыта',
    confirm_block_text: 'Вы уверены, что хотите заблокировать карту? Вы сможете разблокировать её позже.',
    confirm_restore_text: 'Вы уверены, что хотите разблокировать карту?',
    confirm_close_text: 'Вы уверены, что хотите закрыть карту? Остаток средств будет возвращён на счёт.',
    confirm_label_close: 'Закрыть карту',
    confirm_label_ok: 'Подтвердить',
    card_closing_status: 'Закрывается',
    card_not_found: 'Карта не найдена',
    card_err_load: 'Ошибка загрузки реквизитов',
    card_err_op: 'Ошибка операции',
    // CardIssuePage
    issue_page_title: 'Новая карта',
    issue_name_label: 'Название карты (необязательно)',
    issue_name_placeholder: 'Моя карта',
    issue_currency_label: 'Валюта',
    issue_type_label: 'Тип карты',
    issue_standard: 'Стандарт',
    issue_wallet: 'Кошелёк',
    issue_amount_label: 'Начальный баланс',
    issue_continue: 'Продолжить',
    issue_calculating: 'Расчёт...',
    issue_calc_fee: 'Рассчитать комиссию',
    issue_do_issue: 'Выпустить карту',
    issue_usdt_note: 'Начальный баланс вносится в USDT (TRC-20). Курс конвертации USDT определяется в момент зачисления.',
    confirm_issue_title: 'Подтвердить выпуск карты',
    confirm_issue_btn: 'Выпустить',
    card_ready: 'Ваша новая карта готова',
    view_cards: 'Мои карты',
    try_again: 'Повторить',
    view_history: 'История',
    // ProfilePage
    profile_section_title: 'Сервисы',
    profile_name_label: 'Имя',
    profile_phone_label: 'Телефон',
    profile_save: 'Сохранить изменения',
    profile_saving: 'Сохранение...',
    logout: 'Выйти',
    profile_menu_referral: 'Реферальная программа',
    profile_menu_referral_desc: 'Приглашайте друзей и получайте бонусы',
    profile_menu_security: 'Безопасность',
    profile_menu_security_desc: 'Пароль, PIN, биометрия',
    profile_menu_notifications: 'Уведомления',
    profile_menu_notifications_desc: 'Настройки и история уведомлений',
    profile_menu_exchange: 'Обмен валют',
    profile_menu_exchange_desc: 'USDT, USD, EUR конвертация',
    profile_menu_tariffs: 'Тарифы и лимиты',
    profile_menu_tariffs_desc: 'Комиссии и ограничения по картам',
    profile_menu_faq: 'FAQ',
    profile_menu_faq_desc: 'Ответы на частые вопросы',
    profile_menu_support: 'Поддержка',
    profile_menu_support_desc: 'Чат с поддержкой 24/7',
    // ServicesPage
    services_search_placeholder: 'Поиск сервиса...',
    services_no_results: 'Ничего не найдено по запросу',
    services_collapse: 'Свернуть',
    services_expand: 'Развернуть',
    services_whitelist_note: 'Все сервисы работают через whitelist. Платёж на незарегистрированный домен автоматически отклоняется.',
    services_tab_standard: 'Стандарт',
    services_tab_pay: 'Apple/Google Pay',
    // FAQPage
    faq_search_placeholder: 'Поиск по FAQ...',
    faq_no_results: 'Ничего не найдено',
    faq_support_link: 'Не нашли ответ? Напишите в поддержку',
    faq_all: 'Все',
    // TariffsPage
    tariffs_subtitle: 'Выберите подходящий план',
    tariffs_popular: 'Популярный',
    tariffs_total_label: 'Итого для старта',
    tariffs_open_card: 'Открыть эту карту',
    tariffs_faq_title: 'Частые вопросы',
    tariffs_faq_subtitle: 'Ответы на популярные вопросы о картах',
    tariffs_footnote: 'Все суммы указаны в долларах США. Пополнение осуществляется в USDT (TRC-20). Курс конвертации определяется в момент пополнения.',
    plan_standard_subtitle: 'Базовая виртуальная карта USD & EUR для онлайн-платежей',
    plan_pay_subtitle: 'Виртуальная карта с поддержкой Apple Pay и Google Pay',
    // Tariffs plan row labels
    tr_open_cost: 'Стоимость открытия',
    tr_topup_fee: 'Комиссия пополнения USDT',
    tr_conversion: 'Конвертация USDT→USD/EUR',
    tr_min_open: 'Мин. баланс для выпуска',
    tr_min_topup: 'Мин. пополнение',
    tr_max_topup: 'Макс. пополнение',
    tr_3ds: '3D Secure',
    tr_apple: 'Apple Pay',
    tr_google: 'Google Pay',
    tr_support: 'Поддержка 24/7',
    tr_offline: 'Оплата в офлайн-магазинах',
    tr_priority: 'Приоритетная поддержка',
    tr_conversion_rate: 'Курс биржи +1%',
    // ServicesPage
    services_count: 'сервисов',
    services_whitelist_title: 'Вайт-лист',
    services_whitelist_detail: '— гарантия стабильности ваших карт. USD — только онлайн-сервисы, домены, хостинг, подписки, игры. EUR — без ограничений, включая такси и интернет-магазины.',
  },
  en: {
    status_P: 'Pending',
    status_O: 'Processing',
    status_C: 'Complete',
    status_F: 'Failed',
    status_U: 'Unknown',
    kind_DE: 'Deposit',
    kind_WI: 'Withdrawal',
    kind_CO: 'Card Issue',
    kind_CT: 'Card Topup',
    kind_CB: 'Card Block',
    kind_CR: 'Card Restore',
    kind_CC: 'Card Close',
    filter_type: 'Type',
    filter_status: 'Status',
    no_ops: 'No operations yet',
    total: 'total',
    prev: 'Prev',
    next: 'Next',
    history_title: 'History',
    available: 'Available',
    total_balance: 'Total balance',
    greeting: 'Hello',
    recent_ops: 'Recent activity',
    all: 'All',
    active_cards: 'Your cards',
    all_cards: 'All cards',
    action_deposit: 'Deposit',
    action_withdraw: 'Withdraw',
    action_new_card: 'New card',
    action_my_cards: 'My cards',
    action_history: 'History',
    // BottomNav
    nav_home: 'Home',
    nav_cards: 'Cards',
    nav_history: 'History',
    nav_services: 'Services',
    nav_profile: 'Profile',
    // Route titles
    title_cards: 'My Cards',
    title_issue: 'New Card',
    title_deposit: 'Deposit',
    title_withdraw: 'Withdraw',
    title_profile: 'Profile',
    title_referral: 'Referral Program',
    title_security: 'Security',
    title_notifications: 'Notifications',
    title_support: 'Support',
    title_exchange: 'Exchange',
    title_tariffs: 'Tariffs & Limits',
    title_services: 'Services',
    title_faq: 'FAQ',
    title_card_topup: 'Top Up Card',
    title_card_detail: 'Card Details',
    // VirtualCard statuses
    card_status_active: 'Active',
    card_status_frozen: 'Frozen',
    card_status_closed: 'Closed',
    card_hide: 'Hide',
    // CardsPage
    filter_active: 'Active',
    filter_frozen: 'Frozen',
    filter_closed: 'Closed',
    filter_closing: 'Closing',
    no_cards: 'No cards yet',
    no_cards_desc: 'Issue a virtual card for online payments',
    issue_first_card: 'Issue first card',
    issue_new_card: 'Issue new card',
    no_cards_status: 'No cards with this status',
    // DepositPage
    deposit_network: 'Network',
    deposit_scan: 'Scan QR or copy address',
    copy_address: 'Copy address',
    copied: 'Copied!',
    wallet_creating: 'Wallet is being created. Please try again later.',
    deposit_warning: 'Send only USDT (TRC-20) to this address. Sending other tokens will result in permanent loss of funds.',
    // WithdrawPage
    withdraw_available: 'Available to withdraw',
    main_account: 'Main account',
    withdraw_amount_label: 'Withdrawal amount',
    recipient_address: 'Recipient address',
    address_placeholder: 'USDT TRC-20 address (T...)',
    address_err_empty: 'Enter USDT TRC-20 address',
    address_err_invalid: 'Invalid TRC-20 address format',
    fee_calc_title: 'Fee calculation',
    tarif_label: 'Rate',
    fee_label: 'Fee',
    total_debit: 'Total to debit',
    withdraw_network_warning: 'Withdraw only via TRON (TRC-20) network. Other networks are not supported.',
    calc_fee: 'Calculate fee',
    calculating: 'Calculating...',
    do_withdraw: 'Withdraw funds',
    confirm_withdraw_title: 'Confirm withdrawal',
    confirm_withdraw_btn: 'Withdraw',
    amount_label: 'Amount',
    total_label: 'Total',
    withdraw_success_title: 'Request sent!',
    withdraw_success_desc: 'Your request is being processed. You will be notified when complete.',
    to_history: 'Transaction history',
    to_home: 'Home',
    free: 'Free',
    fixed_fee: 'fixed',
    min_fee: 'min',
    // CardDetailPage
    card_credentials: 'Card details',
    btn_show: 'Show',
    btn_hide: 'Hide',
    card_number_label: 'Card number',
    expiry_label: 'Expiry date',
    topup_card: 'Top up card',
    block_card: 'Block card',
    unblock_card: 'Unblock card',
    close_card: 'Close card',
    return_to_card: 'Back to card',
    card_blocking: 'Blocking card...',
    card_blocked_done: 'Card blocked',
    card_restoring: 'Restoring card...',
    card_restored_done: 'Card restored',
    card_closing_op: 'Closing card...',
    card_closed_done: 'Card closed',
    confirm_block_text: 'Are you sure you want to block the card? You can unblock it later.',
    confirm_restore_text: 'Are you sure you want to unblock the card?',
    confirm_close_text: 'Are you sure you want to close the card? The remaining balance will be returned to your account.',
    confirm_label_close: 'Close card',
    confirm_label_ok: 'Confirm',
    card_closing_status: 'Closing',
    card_not_found: 'Card not found',
    card_err_load: 'Failed to load card details',
    card_err_op: 'Operation error',
    // CardIssuePage
    issue_page_title: 'New Card',
    issue_name_label: 'Card name (optional)',
    issue_name_placeholder: 'My Card',
    issue_currency_label: 'Currency',
    issue_type_label: 'Card type',
    issue_standard: 'Standard',
    issue_wallet: 'Wallet',
    issue_amount_label: 'Initial balance',
    issue_continue: 'Continue',
    issue_calculating: 'Calculating...',
    issue_calc_fee: 'Calculate fee',
    issue_do_issue: 'Issue card',
    issue_usdt_note: 'Initial balance is deposited in USDT (TRC-20). Conversion rate is determined at the time of deposit.',
    confirm_issue_title: 'Confirm card issue',
    confirm_issue_btn: 'Issue card',
    card_ready: 'Your new card is ready',
    view_cards: 'My cards',
    try_again: 'Try again',
    view_history: 'History',
    // ProfilePage
    profile_section_title: 'Services',
    profile_name_label: 'Name',
    profile_phone_label: 'Phone',
    profile_save: 'Save changes',
    profile_saving: 'Saving...',
    logout: 'Log out',
    profile_menu_referral: 'Referral Program',
    profile_menu_referral_desc: 'Invite friends and earn bonuses',
    profile_menu_security: 'Security',
    profile_menu_security_desc: 'Password, PIN, biometrics',
    profile_menu_notifications: 'Notifications',
    profile_menu_notifications_desc: 'Settings and notification history',
    profile_menu_exchange: 'Currency Exchange',
    profile_menu_exchange_desc: 'USDT, USD, EUR conversion',
    profile_menu_tariffs: 'Tariffs & Limits',
    profile_menu_tariffs_desc: 'Fees and card limits',
    profile_menu_faq: 'FAQ',
    profile_menu_faq_desc: 'Frequently asked questions',
    profile_menu_support: 'Support',
    profile_menu_support_desc: 'Chat with 24/7 support',
    // ServicesPage
    services_search_placeholder: 'Search service...',
    services_no_results: 'Nothing found for',
    services_collapse: 'Collapse',
    services_expand: 'Expand',
    services_whitelist_note: 'All services operate via whitelist. Payments to unregistered domains are automatically rejected.',
    services_tab_standard: 'Standard',
    services_tab_pay: 'Apple/Google Pay',
    // FAQPage
    faq_search_placeholder: 'Search FAQ...',
    faq_no_results: 'Nothing found',
    faq_support_link: "Didn't find an answer? Contact support",
    faq_all: 'All',
    // TariffsPage
    tariffs_subtitle: 'Choose the right plan',
    tariffs_popular: 'Popular',
    tariffs_total_label: 'Total to start',
    tariffs_open_card: 'Open this card',
    tariffs_faq_title: 'FAQ',
    tariffs_faq_subtitle: 'Answers to popular questions about cards',
    tariffs_footnote: 'All amounts are in USD. Top-up is made in USDT (TRC-20). The conversion rate is determined at the time of top-up.',
    plan_standard_subtitle: 'Basic virtual card USD & EUR for online payments',
    plan_pay_subtitle: 'Virtual card with Apple Pay and Google Pay support',
    // Tariffs plan row labels
    tr_open_cost: 'Opening fee',
    tr_topup_fee: 'USDT top-up fee',
    tr_conversion: 'USDT→USD/EUR conversion',
    tr_min_open: 'Min. balance to issue',
    tr_min_topup: 'Min. top-up',
    tr_max_topup: 'Max. top-up',
    tr_3ds: '3D Secure',
    tr_apple: 'Apple Pay',
    tr_google: 'Google Pay',
    tr_support: '24/7 support',
    tr_offline: 'Offline store payments',
    tr_priority: 'Priority support',
    tr_conversion_rate: 'Exchange rate +1%',
    // ServicesPage
    services_count: 'services',
    services_whitelist_title: 'Whitelist',
    services_whitelist_detail: '— guarantees stability of your cards. USD — online services, domains, hosting, subscriptions, games only. EUR — no restrictions, including taxi and online stores.',
  },
} as const;

type TKey = keyof typeof T.ru;

interface LangContextType {
  lang: Lang;
  toggleLang: () => void;
  t: (key: TKey) => string;
}

const LangContext = createContext<LangContextType>({
  lang: 'ru',
  toggleLang: () => {},
  t: (key) => T.ru[key],
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('ru');
  const toggleLang = () => setLang((l) => (l === 'ru' ? 'en' : 'ru'));
  const t = (key: TKey): string => T[lang][key];
  return <LangContext.Provider value={{ lang, toggleLang, t }}>{children}</LangContext.Provider>;
}

export function useLang() {
  return useContext(LangContext);
}
